### ISSUE TITLE
[Team 2] Pick Design Patterns

### ISSUE THREAD

**Issue by AngelUMICH** [bkochuna/ners570f21-Lab06#1]
**Picking design patterns:**
Design patterns are needed to identify and layout of the high-level design of the code with a reusable common/general known solution. Picking the correct design patterns make the transformation to code more direct and helps prevent redesigning the code during the manual coding process. This is also one of the requirements for the class to identify and choose design patterns.

**Things to be done**
(must identify type of 3 patterns and draft of patterns, and official UML documents (on a separate issues #15) )
- [x] creational - creating instances of the code
- [x] structural - interfacing and attribute stuff (Facade)
- [x] behavioral - how the classes interact with each other
- [x] Diagrams are documented for each pattern #15 

**Definition of Done**

Finished when all boxes are ticked (meaning, type of patterns listed and drafts of patterns are attached)
This includes official UML patterns created in issue #15. 

Must be reviewed by three assignees and @bkochuna to be considered closed
- [ ] Reveiwer1 : <user>
- [ ] Reveiwer2 : <user>
- [ ] Reveiwer3 : <user>
- [ ] Instructor: @bkochuna 

**Review Criteria**
- [ ] The library shall be flexible in providing sparse matrices in several formats.
- [ ] The library shall make use of Object-Oriented Design (and Programming)
- [ ] The library shall make use of Design Patterns
- [ ] The library shall be extensible
- [ ] The library shall use a CMake based build system
- [ ] The library shall use C++ and any of C or Fortran only.

**Comment by gang525** [comment]
Structural = Adapter (convert the interface of others to a common one)

**Comment by tyjoto** [comment]
Here is the structural pattern of how the classes interface


![image_16783617](https://user-images.githubusercontent.com/45111310/137155059-6bbe798d-60bf-43eb-a9ae-73ebbd5b3e47.jpg)
